cargo setup and functionalities for erc165
rainlanguage/rain.erc pull request #3
Opened 2024-05-21 14:21 UTC by rouzwelt

## Motivation
setup cargo and functionalities for erc165

## Solution

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [x] unit-tested any new functionality
- [x] linked any relevant issues or PRs

2024-05-23 09:22 UTC, thedavidmeister requested changes

2024-05-23 09:22 UTC, thedavidmeister commented on src/erc165/mod.rs
> +        let erc165_supported_contract =
can we split these two separate test cases into separate tests?

2024-05-23 09:22 UTC, thedavidmeister commented on src/erc165/mod.rs
> +    async fn test_supports_erc165() {
can we have a test for a contract that returns true for erc165 calls but is _not_ an erc165 contract?

that's the whole point of doing the multi step check but we don't test it

2024-05-24 00:25 UTC, rouzwelt commented on src/erc165/mod.rs
> +        let erc165_supported_contract =
ofc, please refer to new commits

2024-05-24 03:39 UTC, thedavidmeister requested changes

2024-05-24 03:39 UTC, thedavidmeister commented on test-contracts/erc165/InvalidERC165.sol
> +    function externalFn() external pure returns (bool) {
what is the point of these internal and external fns?

2024-05-24 03:39 UTC, thedavidmeister commented on test-contracts/erc165/InvalidERC165.sol
> +pragma solidity >=0.6.0;
=0.8.25 is what we currently use for test contracts

2024-05-24 16:09 UTC, rouzwelt commented on test-contracts/erc165/InvalidERC165.sol
> +    function externalFn() external pure returns (bool) {
nothing, just put some fns there

2024-05-25 09:08 UTC, thedavidmeister requested changes

2024-05-25 09:08 UTC, thedavidmeister commented on src/erc165/mod.rs
> +        let anvil = Anvil::new().spawn();
is it possible to just mock the responses rather than use a real anvil process?

2024-05-25 16:34 UTC, rouzwelt commented on src/erc165/mod.rs
> +        let anvil = Anvil::new().spawn();
hmm i think it is possible, but im not sure if it really helps with anything? i mean what is it that we are testing then? returning false value as mocked, and then check if the fn also returns false?
i think in this case using an evm is important because i think one of the main points of this test is to make sure we are doing the correct onchain calls with correct calldata based on erc165 specs, but besides that, there is not much else to these fns tbh to test

2024-05-25 17:23 UTC, thedavidmeister commented on src/erc165/mod.rs
> +        let anvil = Anvil::new().spawn();
@rouzwelt correct, it's a simple feature, it's not supposed to be complex to write or test

mocking contract return values should have the same outcome from a testing perspective as anvil, so why not?

cc @hardyjosh

2024-05-28 05:54 UTC, thedavidmeister requested changes

2024-05-28 05:54 UTC, thedavidmeister commented on src/erc165/mod.rs
> +                    "jsonrpc": "2.0",
isn't there something typed that can handle this rather than strings?

2024-05-28 13:15 UTC, rouzwelt commented on src/erc165/mod.rs
> +                    "jsonrpc": "2.0",
not really, at least with current deps libs, in ethers it is raw serdejson Value btw, 
unless you want me to make a struct or something for it?

2024-05-29 11:20 UTC, thedavidmeister requested changes

2024-05-29 11:20 UTC, thedavidmeister commented on src/erc165/mod.rs
> +                    "jsonrpc": "2.0",
@rouzwelt correct, i don't want piles of stringly typed copypasta boilerplate throughout the codebase

2024-05-31 05:51 UTC, thedavidmeister requested changes

2024-05-31 05:51 UTC, thedavidmeister commented on src/erc165/mod.rs
> +    fn get_rpc_request_body(address: Address, data: &str) -> String {
can we use https://github.com/foundry-rs/foundry/blob/master/crates/anvil/core/src/eth/mod.rs#L44 ?

2024-05-31 16:25 UTC, rouzwelt commented on src/erc165/mod.rs
> +    fn get_rpc_request_body(address: Address, data: &str) -> String {
hmm, maybe, but is it really needed for this small crate? to add foundry which is a big dep, just for the purpose of a few tests?

2024-05-31 16:33 UTC, rouzwelt commented on src/erc165/mod.rs
> +    fn get_rpc_request_body(address: Address, data: &str) -> String {
I personally think it is fine having some json strings on these tests, I understand that having a typed structure is better, but I think for now, it seems ok to have that json, maybe when/if this repo grows and there are more tests and stuff, then we cna just go ahead with adding foundry in.

2024-05-31 21:27 UTC, thedavidmeister requested changes

2024-05-31 21:27 UTC, thedavidmeister commented on src/erc165/mod.rs
> +    fn get_rpc_request_body(address: Address, data: &str) -> String {
@rouzwelt i'm looking for a standard way to mock rpc calls in rust, and this seems to be what i've been asking for

2024-06-03 03:36 UTC, rouzwelt commented
@thedavidmeister  used some structs and types form `ethers-providers` repo, as the suggested lib required a whole series of typecasting, since it was based on alloy client repo and our usage is based on ethers.

ideally we can put these in typecast repo, and once we switch to alloy client from ethers, we can just use alloy rpc types.

2024-06-03 06:10 UTC, thedavidmeister requested changes

2024-06-03 06:10 UTC, thedavidmeister commented on src/erc165/mod.rs
> +    #[derive(Serialize, Deserialize, Debug)]
if this is our _global standard way of mocking RPC in rust across all crates_ then it should not be in this crate

2024-06-03 21:37 UTC, rouzwelt commented
todo:

- [ ] - once the PR: https://github.com/rainlanguage/alloy-ethers-typecast/pull/29 is merged, update the dependency commit hash to the merged commit of main branch

2024-06-06 06:44 UTC, thedavidmeister commented
> todo:
> 
> * [ ]  - once the PR: [rpc types alloy-ethers-typecast#29](https://github.com/rainlanguage/alloy-ethers-typecast/pull/29) is merged, update the dependency commit hash to the merged commit of main branch

upstream branch is merged

2024-06-07 06:46 UTC, thedavidmeister requested changes

2024-06-07 06:46 UTC, thedavidmeister commented on src/erc165/mod.rs
> +    fn get_request_body(id: u64, transaction: &AlloyTransactionRequest) -> String {
if our rpc abstraction is right upstream we shouldn't need this here

2024-06-08 07:25 UTC, rouzwelt commented on src/erc165/mod.rs
> +    fn get_request_body(id: u64, transaction: &AlloyTransactionRequest) -> String {
it is correct upstream, this is just a simlle helper here, i can mive it into each call on tests, but it is easier to have this

2024-06-09 06:43 UTC, thedavidmeister commented on src/erc165/mod.rs
> +    fn get_request_body(id: u64, transaction: &AlloyTransactionRequest) -> String {
you're missing the point, if we need a "simple helper" here then we need it everywhere

i don't think the "simple helper" is needed at all tbh, but if you want to keep it, please put it where our _global standard way for mocking RPCs_ lives, not here

2024-06-10 07:16 UTC, thedavidmeister requested changes

2024-06-10 07:16 UTC, thedavidmeister commented on src/erc165/mod.rs
> +        && supports_erc165_check2(client, contract_address).await
this function might be on a hot performance path and these checks might have to hit a remote rpc

can we do them concurrently rather than awaiting the first before starting the second call?

2024-06-10 13:14 UTC, rouzwelt commented on src/erc165/mod.rs
> +        && supports_erc165_check2(client, contract_address).await
hmm based on specs it should be done in order, but from the coding side of things having them async should work fine too

2024-06-10 13:17 UTC, rouzwelt commented on src/erc165/mod.rs
> +        && supports_erc165_check2(client, contract_address).await
but not sure if that makes sense, because if the first check is false, then it wont even go for second check, and based on specs thats the whole point of it i guess

2024-06-10 17:53 UTC, rouzwelt commented on src/erc165/mod.rs
> +        && supports_erc165_check2(client, contract_address).await
would that be ok if it goes a bit against the specs?

2024-06-10 18:26 UTC, thedavidmeister requested changes

2024-06-10 18:26 UTC, thedavidmeister commented on src/erc165/mod.rs
> +        && supports_erc165_check2(client, contract_address).await
@rouzwelt the specs are talking about onchain logic

these are _static_ calls which means read only

if you do two read only calls from the same starting state, e.g. the same block, then you'll always get the same answer regardless of ordering of the calls

you can check the boolean logic of the read only results sequentially as `1 && 2` without forcing the actual fetching from the RPC to be sequential

2024-06-11 07:42 UTC, thedavidmeister requested changes

2024-06-11 07:42 UTC, thedavidmeister commented on foundry.toml
> +[profile.default]
if we're mocking everything then we don't need any foundry code right?

rainix isn't even running sol checks anyway

2024-06-11 16:07 UTC, rouzwelt commented on foundry.toml
> +[profile.default]
oh right, yes, forgot to delete this

2024-06-12 16:43 UTC, thedavidmeister approved these changes

2024-06-12 16:44 UTC, merged