add xor selectors trait
rainlanguage/rain.erc pull request #4
Opened 2024-06-17 20:39 UTC by rouzwelt

## Motivation
add a trait for types that implement SolInterface, so that there is a mthod for alloy generated bindings when the trait is in scope.

## Solution
Add the trait and impl for the T: SolInterface

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [x] unit-tested any new functionality
- [x] linked any relevant issues or PRs

2024-06-17 21:15 UTC, hardyjosh approved these changes

2024-06-18 10:16 UTC, hardyjosh requested changes
@rouzwelt please make the error an enum with `thiserror:Error` derived on it. we can remove anyhow and use the standard `Result`

2024-06-19 01:14 UTC, rouzwelt commented
> @rouzwelt please make the error an enum with `thiserror:Error` derived on it. we can remove anyhow and use the standard `Result`

applied

2024-06-19 09:33 UTC, hardyjosh commented on Cargo.toml
> +anyhow = "1.0.86"
can we remove this dep now?

2024-06-19 19:41 UTC, hardyjosh approved these changes

2024-06-19 19:42 UTC, merged